name: Test progenitor-generated client
on:
  pull_request:
jobs:
  run-example:
    name: "Test example on progenitor-generated client"
    runs-on: ubuntu-latest
    timeout-minutes: 5 
    steps:
      - uses: actions/checkout@v7
      - name: Build and run
        run: |
          cd example && cargo test -- --nocapture
