name: Regenerate client

permissions:
  pull-requests: write
  contents: write

on:
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 1 hour after midnight
  workflow_dispatch:

jobs:
  regenerate-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Regenerate client
        run: |
          cargo install cargo-progenitor --git https://github.com/PolyProgrammist/progenitor --branch patch_rustfmt
          ./generate.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: regenerate client
          token: ${{ secrets.NEARPROTOCOL_CI_PR_ACCESS }}
